/*
 * Project name:
     FISHER_GUI.vtft
 * Generated by:
     Visual TFT
 * Date of creation
     1/28/2013
 * Time of creation
     10:05:55 AM
 * Test configuration:
     MCU:             STM32F407VG
     Dev.Board:       mikromedia_for_STM32_M4
                      http://www.mikroe.com/eng/products/view/869/mikromedia-for-stm32-m4/
     Oscillator:      140000000 Hz
     SW:              mikroC PRO for ARM
                      http://www.mikroe.com/eng/products/view/752/mikroc-pro-for-arm/
 */


#include "hepsi.h"

void main() {

  Start_TP();
  
  reset();
  ClassPopulation = 5;
  TrainPicture = ClassNumber * ClassPopulation;
  TestPicture=50;
  N=TrainPicture/2;
  TetaC=400;
  
  while (1) {
    Check_TP();

  }

}