/*
 * Project name:
     DCVA_GUI.vtft
 * Generated by:
     Visual TFT
 * Date of creation
     2/8/2013
 * Time of creation
     6:34:40 AM
 * Test configuration:
     MCU:             STM32F407VG
     Dev.Board:       mikromedia_for_STM32_M4
                      http://www.mikroe.com/eng/products/view/869/mikromedia-for-stm32-m4/
     Oscillator:      140000000 Hz
     SW:              mikroC PRO for ARM
                      http://www.mikroe.com/eng/products/view/752/mikroc-pro-for-arm/
 */

#include "DCVA_GUI_objects.h"


void main() {

  Start_TP();

  while (1) {
    Check_TP();

  }
}
