/*
 * Project name:
     PCA_FLDA_GUI.vtft
 * Generated by:
     Visual TFT
 * Date of creation
     1/31/2013
 * Time of creation
     10:31:58 PM
 * Test configuration:
     MCU:             STM32F407VG
     Dev.Board:       mikromedia_for_STM32_M4
                      http://www.mikroe.com/eng/products/view/869/mikromedia-for-stm32-m4/
     Oscillator:      140000000 Hz
     SW:              mikroC PRO for ARM
                      http://www.mikroe.com/eng/products/view/752/mikroc-pro-for-arm/
 */

#include "PCA_FLDA_GUI_objects.h"

void main() {

  Start_TP();

  while (1) {
    Check_TP();

  }

}
